language: python
python:
- '3.5'
before-script:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  app: fishingday
  api_key:
    secure: cugicP50CPRzQf2uGg2D4m4TBUi7W3eSGov3kTQNc+MVbo81oUy6e8ZTgEpDpkXywhY5jO4TtS23tD0IJGJgtX2L/IV95fFAK81WajbEB4kXyL230QdppF+jYpSe7Gy90J681AxWEyImQrQ6ksoQrTFSdpfiq2AIvCOp8Io0eWiG5y+wRFlsDoyYE8aLQBdER9w5btunEXn1bjWsi0SLs6bMeUegK5ADjkQc70l1jCWi05Yr3uOWJNZynZlOR7yR1KmSqojJOE39v2hRteZnwPtAzo1E4KZumY8f6iu3vkNHenCc2lCQ/qee+/BGcHYK09kf0z7uInrmjJXtavMPtSHMoRhhVlY7feumYlosIS4ZPFFMcJ0vfSBlMJ8IhbN/12fuU/Fqss5IYMaMxVah+zhkA2JVvendS1+iX1ZEiksNSITislco8bXm4QkOQcYcXkz1JQCnYbGrdCg2gTGwdleCzCVEMRR8JvUrBWOde+ODA4ub+f72Nc39J7QsHiObrYdwjH2sGLzTGwj14KJ/e3eA5kQQi8YRhlb/notYfiPIWyiZQLZ7AZ8n8L8OwF/IuQiYva2i/DtRSz1anlgZPTtJ2/k8ddW3VfEyUT+rDGP7M99jMoD9Nl3DKAYLbu/hbA7iKL/hNEdfco6ZciJQyPFltqE/4fo97/l7B1+I3hA=
