language: python
python:
- '3.5'
before-script:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  app: fishingday
  api_key:
    secure: eZF64NTF8Lb3K3HZicDAYkoMcB07YoDogo3mUOMvScP5yLT9jz6l3T/jTJIuDtbP1nIgqVVhybpYj5YykpQRewOj8NkaxqJ7g24EwTwknbaGJxxXd30AUDXaXqFZdS89JXcsgGrpBVPHpJi0KG6kNXCcxV+5X03u+pwSgjSjdNdC8lHOUrLm1thPb23FYV1ZtB1CiYv6fFY8uxMNHNvHQE2F7YJCqVh6QGF7XfEC02MJjvYC6aKpdb2YCKAcXYnZ4L4XfxMOyyjHinyxVM9m2C+eZLT8dLHTgDCT8Dve2clb+QCyrJlJYZERIgQ2TXlRnO6KEueJW5mhjo336DKlfmA1XhuID4YUGuaC6rROcKgSldzNjTALxXhYXAvzsZo1B9NLLLEL04hTc77fSRtuUT3BM4Az3XrGfF+FqYogsEGgutFWRtGaBmobSjsfSqab7DiJBmqf1709jmPYDiTHVRClOjslCcRPuvrv12ttJa9SCPRjWzPTj3khG3a8u0g1VXhE5pnMZUmegmynu3MsNUG4iWIowEp6snSxlq/LOkUoAGVZEyDRvjvt0oEaL69HZAzWSl/lDiWxj8LrpsWEl0YyoA8gCXq0xpjM9OvSerGN78UbfT7zXja3ZHEDdsr4j/GEN5qLKUFigYcdbOfOoqJmdDoofOwqnl1UY1w9cwY=
