language: python
python:
- '3.5'
before-script:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  app: fishingday
  api_key:
    secure: FxWYLeZilA/iKvjG8mfl4Kk+IBV8HvcJyZmVFtrBRcaE9si8wHA1AlONDrupnLnqV+Zc2nKFkGRusyFXbRwD9DMOH+sV7CQnP8Yhkd+TUWxWc2BgC9uyvTC7GJUbYXqC1lsaPKVAGTs9zBvKLXr+EXbwHqKhCs46N+NtqZ29Y7cbyybPjCenKIUY//v6JCvTMklh/ZvChJaThd2KymTaTNCuMQuF043VOoIjVwbZHUiY2PzFF+7CBwj2NUkB9i+vNDMAHnWZMA33JtwA3OcONS3oDh5JUYq9XgzXFsGHY/h/PvU2u1hVb23VSNB7HPexepmVaZWnQtX9wEm8KPGR/JId7F9kz4k8u8iVb7b3v7lfdvja1PclQzENzKRiSSdZSsS/3G4/KKZP/zr4/cghae03M2sybMbidyA5hKaelIb9gMRplz9D8rrBTRjjVmlxIVM6jv7Kyfq4HReGUrCK9+xAMjJvMlYizhzGf3YCdadaXeJTbyioY6RDYPaWv6wEsrCn8OZThfHxUtmuSftYg/TRw+kLrP31ZxTgElJyMBk8Iwq3OCl/db7UycXRbnOdVxjxQYvEQ8kzOGH+3iKox+O3iaTUk+MbrjDwA6FO/Oc+5oxJB7iJGMLbff/8Yx2OyO+l+WLhla1pm43YlMbkjq2qzWyLrnvBS9B99Ni+hKU=
